version: "3.9"

services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./html:/usr/share/nginx/html
            - ./certs:/etc/nginx/certs:ro
            - ./vhost:/etc/nginx/vhost.d
            - ./conf:/etc/nginx/conf.d

    ssl:
        image: nginxproxy/acme-companion
        volumes_from:
            - nginx-proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./certs:/etc/nginx/certs:rw
            - ./acme:/etc/acme.sh
        environment:
            - DEFAULT_EMAIL=jequinterope@unal.edu.co

    dns:
        image: linuxserver/duckdns
        restart: unless-stopped
        environment:
            - TZ=America/Bogota
            - SUBDOMAINS=imagine-swarch,soap-imagine
            - TOKEN=fcbc2ad6-edc2-4bc5-845f-cc90a8523dcd
            - LOG_FILE=false
    
    imagine-interface:
        image: nisanchezva/imagine_interface
        restart: on-failure
        environment:
            - GRAPHQL_CLIENT_URL=http://api-gateway:5000/graphql
            - SERVER_PORT=1111
            - VIRTUAL_HOST=soap-imagine.duckdns.org
            - LETSENCRYPT_HOST=soap-imagine.duckdns.org
            - VIRTUAL_PORT=1111
        expose:
            - "1111"
        depends_on:
            - api-gateway

    imagine-wa:
        image: nisanchezva/imagine_wa
        restart: on-failure
        expose:
            - "4500"
        environment:
            - LETSENCRYPT_HOST=imagine-swarch.duckdns.org
            - API_GATEWAY_URL=images-ms:5000
            - STORAGE_MS_URL=storage-ms:1234
            - VIRTUAL_HOST=imagine-swarch.duckdns.org
            - VIRTUAL_PORT=4500
        depends_on:
            - api-gateway

    api-gateway:
        image: nisanchezva/api_gateway
        restart: on-failure
        expose:
            - "5000"
        environment:
            - COLLECTIONS_MS_URL=collections-ms:8000
            - COMMENTS_MS_URL=network-ms:3123
            - STORAGE_MS_URL=storage-ms:1234
            - IMAGES_MS_URL=images-ms:8080
            - VOTES_MS_URL=network-ms:3123
            - PROFILE_MS_URL=profile-ms:80
            - AUTH_MS_URL=auth-ms:3000
        depends_on:
            - collections-ms
            - storage-ms
            - network-ms
            - profile-ms
            - images-ms
            - auth-ms

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672

    storage-ms:
        image: rhiino/imagine_storage_ms:v2
        restart: on-failure
        environment:
            - GCS_BUCKET=arqui
            - GCS_FILE=clean-framework-340802-d71f73f1694f.json
            - GCS_PROJECT_ID=clean-framework-340802
            - GCS_ENDPOINT=https://storage.googleapis.com/
            - RABBITMQ_HOST=rabbitmq
        ports:
            - "1234:1234"
        depends_on:
            - rabbitmq

    ms-sql-server:
        image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Pa##w0rd2020"
            MSSQL_PID: Express
        expose:
            - "1433"

    profile-ms:
        image: demonmasks/imagine_profile_ms
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
        expose:
            - "80"
        depends_on:
            - ms-sql-server

    ldap:
        image: osixia/openldap:1.1.8
        container_name: ldap
        environment:
            COMPOSE_HTTP_TIMEOUT: 200
            LDAP_LOG_LEVEL: "256"
            LDAP_ORGANISATION: "Imagine"
            LDAP_DOMAIN: "imagine.unal.edu.co"
            LDAP_BASE_DN: ""
            LDAP_ADMIN_PASSWORD: "admin"
            LDAP_CONFIG_PASSWORD: "config"
            LDAP_READONLY_USER: "false"
            #LDAP_READONLY_USER_USERNAME: "readonly"
            #LDAP_READONLY_USER_PASSWORD: "readonly"
            LDAP_BACKEND: "hdb"
            LDAP_TLS: "true"
            LDAP_TLS_CRT_FILENAME: "ldap.crt"
            LDAP_TLS_KEY_FILENAME: "ldap.key"
            LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
            LDAP_TLS_ENFORCE: "false"
            LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
            LDAP_TLS_PROTOCOL_MIN: "3.1"
            LDAP_TLS_VERIFY_CLIENT: "demand"
            LDAP_REPLICATION: "false"
            #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
            #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
            #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
            LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
            LDAP_SSL_HELPER_PREFIX: "ldap"
        tty: true
        stdin_open: true
        volumes:
            - /var/lib/ldap
            - /etc/ldap/slapd.d
            - /container/service/slapd/assets/certs/
        ports:
            - "389:389"
            - "636:636"
        hostname: "arqsoft.unal.edu.co"

    phpldapadmin:
        image: osixia/phpldapadmin:latest
        container_name: ldap_client
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: "ldap"
            PHPLDAPADMIN_HTTPS: "false"
        ports:
            - "8085:80"
        links:
            - ldap

    auth-db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: arqui
            POSTGRES_USER: arqui
            POSTGRES_DB: imagine_auth_db

    auth-ms:
        image: dacperezce/imagine_auth_ms:v2
        command: bash -c "rm -f tmp/pids/server.pid && ls && bundle exec rails s -p 3000 -b '0.0.0.0'"
        ports:
            - "3000:3000"
        environment:
            - LDAP_HOST=ldap
        depends_on:
            - auth-db
            - ldap

    network-ms:
        image: josteda99/imagine_network_ms
        restart: on-failure
        expose:
            - "3123"

    images-db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: imagine_images_db
            MYSQL_PASSWORD: root
            MYSQL_USER: admin
        expose:
            - "3306"

    images-ms:
        image: nisanchezva/imagine_images_ms
        restart: on-failure
        expose:
            - "8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://images-db:3306/imagine_images_db?autoReconnect=true&useSSL=false
            SPRING_DATASOURCE_USERNAME: "root"
            SPRING_DATASOURCE_PASSWORD: "root"
            SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
            SPRING_RABBITMQ_HOST: rabbitmq
        depends_on:
            - images-db

    collections-ms:
        image: lalopaex/imagine_collections_ms
        restart: on-failure
        expose:
            - "8000"
        environment:
            - NEO4J_BOLT_URL=collections-db:7687
            - NEO4J_PASSWORD=test
        depends_on:
            - collections-db

    collections-db:
        image: neo4j:latest
        expose:
            - "7687"
            - "7474"
        restart: on-failure
        environment:
            - NEO4J_AUTH=neo4j/test
